name: PHP Compatibility

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.2, 7.3, 8.0, 8.1, 8.2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, zip

    - name: Install dependencies
      run: composer install

    - name: Run tests
      run: php vendor/bin/phpunit
